---
title: "DE_analysis"
author: "Milena Trabert"
date: "2026-03-27"
output: html_document
---

## load libraries
```{r}
# install all dependencies
if (FALSE){
  if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  BiocManager::install("DESeq2") # compiled from source 
  BiocManager::install("edgeR")
  # install tidyverse (ggplot2 is in tidyverse)
  install.packages("tidyverse") 
  install.packages("gtable") 
  install.packages("VennDiagram") 
}
library(tidyverse)
library(ggplot2)
library(edgeR)
library(limma)
library(VennDiagram)
```

## prepare data
```{r}
in_filename <- "/Users/miltr339/work/PhD_code/PhD_chapter4/data/gene_counts_standard.txt"
out_norm_counts <- "/Users/miltr339/work/PhD_code/PhD_chapter4/data/gene_counts_normalized.tsv"
metadata <- "/Users/miltr339/work/PhD_code/PhD_chapter4/data/larvae_metadata.csv"

## load data
  count_data <- read.csv(in_filename, header = TRUE, sep = "\t",comment.char = "#", check.names = FALSE)
  count_data <- count_data %>% select(-one_of('Chr','Start','End','Strand','Length')) 
  # make the Geneid the row id 
  count_data <- count_data %>% remove_rownames %>% column_to_rownames(var="Geneid")
## meta data
  DE_metadata_all <- read.csv(metadata, header = TRUE, sep = ",",comment.char = "#")
  # only include metadata when the samples are in the counts
  meta_data <- DE_metadata_all[which((DE_metadata_all$ID %in% names(count_data))==TRUE), ]
  meta_data <- meta_data %>% remove_rownames %>% column_to_rownames(var="ID")
  # reorder so it's in the same order as the count data columns
  meta_data <- meta_data[names(count_data),]
  # check assumptions, should be TRUE
  all(colnames(count_data) %in% rownames(meta_data))
  
## normalize library sizes
  # make sample groups that reflect line and day
  groups <- factor(paste(meta_data$line, meta_data$sex, meta_data$day, sep="_"))
  # read data into data structure
  y <- DGEList(counts=count_data, group=groups)
  #dim(y)
  #[1] 15702    82
  
## filter out low count genes
  # minimum count of 5 in at least some samples, and a minimum total count of 15 across all samples 
  keep <- filterByExpr(y, group=meta_data$line, min.count=5, min.total.count=15)
  y <- y[keep, , keep.lib.sizes=FALSE]
  y$samples$lib.size <- colSums(y$counts) # recompute library sizes
  # dim(y)
  # [1] 11641    82
  
## normalize by library sizes
  y <- calcNormFactors(y)
  
## export normalized counts to file
  log_norm_counts <- cpm(y,normalized.lib.sizes = TRUE,log = TRUE,prior.count = 1)
  write.table(log_norm_counts,file = out_norm_counts, sep = "\t",quote = FALSE)# ,col.names = NA)
  #### !!! manually add first header "geneID" to the file !!! ###
  
```
See Python scripting for the PCA plots


# basic DE with only the males

I will start with DE analysis that involves only the males to get an idea of what is going on. 

## partition and prepare data

```{r} 
## filter count data to only include males 
counts_M <- count_data[,grepl("-M_", colnames(count_data))]
## adjust metadata
meta_data <- DE_metadata_all[which((DE_metadata_all$ID %in% names(counts_M))==TRUE), ]
meta_data <- meta_data %>% remove_rownames %>% column_to_rownames(var="ID")
# reorder so it's in the same order as the count data columns
meta_data <- meta_data[names(counts_M),]
# check assumptions, should be TRUE
all(colnames(counts_M) %in% rownames(meta_data))

# make sample groups that reflect line and day
groups <- factor(paste(meta_data$line, meta_data$day, sep="_"))
# read data into data structure
y <- DGEList(counts=counts_M, group=groups)

## filter out low count genes
# filter by only line group and not day, since we aren't sure how the expression changes between days and we don't want to remove genes that are only rarely expressed
keep <- filterByExpr(y, group=meta_data$line, min.count=5, min.total.count=15)
  y <- y[keep, , keep.lib.sizes=FALSE]
  y$samples$lib.size <- colSums(y$counts) # recompute library sizes
  
# normalize by library sizes
y <- calcNormFactors(y)

# estimate dispersion
MM <- model.matrix(~0 + groups)
colnames(MM) <- c("SL1_14", "SL1_16", "SL1_18", "SL3_14",  "SL3_16", "SL3_18")
rownames(MM) <- colnames(y)

y <- estimateDisp(y, MM)
plotBCV(y)
```

## do Differential expression

I will test several contrasts, where each contrast is SL1-SL3 within the same day
```{r}
fit <- glmFit(y, MM)

my.contrasts <- makeContrasts(
day14 =	SL1_14 - SL3_14, 
day16 =	SL1_16 - SL3_16, 
day18 = SL1_18 - SL3_18,
levels=MM)

## fit model for all contrasts
lrt14 <- glmLRT(fit, contrast=my.contrasts[,"day14"])
summary(de14<-decideTestsDGE(lrt14, p.value=0.05, lfc=1)) 
lrt16 <- glmLRT(fit, contrast=my.contrasts[,"day16"])
summary(de16<-decideTestsDGE(lrt16, p.value=0.05, lfc=1)) 
lrt18 <- glmLRT(fit, contrast=my.contrasts[,"day18"])
summary(de18<-decideTestsDGE(lrt18, p.value=0.05, lfc=1)) 

## save DE genes to table
### different number of lines than the DE genes in the summaries above?
Tags14 <- topTags(lrt14, n=Inf, p.value=0.05)						
Tags14 <- Tags14$table
Tags14 $Gene <- rownames(Tags14)
write.table(Tags14, file="/Users/miltr339/work/PhD_code/PhD_chapter4/data/DE_genes_M_1-3_day14.txt", sep="\t")	

Tags16 <- topTags(lrt16, n=Inf, p.value=0.05)						
Tags16 <- Tags16$table
Tags16 $Gene <- rownames(Tags16)
write.table(Tags16, file="/Users/miltr339/work/PhD_code/PhD_chapter4/data/DE_genes_M_1-3_day16.txt", sep="\t")	

Tags18 <- topTags(lrt18, n=Inf, p.value=0.05)						
Tags18 <- Tags18$table
Tags18 $Gene <- rownames(Tags18)
write.table(Tags18, file="/Users/miltr339/work/PhD_code/PhD_chapter4/data/DE_genes_M_1-3_day18.txt", sep="\t")	

## make venn diagram to show the overlap
library(VennDiagram)

de14<-decideTestsDGE(lrt14, p.value=0.05, lfc=1) 
detags14 <- rownames(y)[as.logical(de14)]

de16<-decideTestsDGE(lrt16, p.value=0.05, lfc=1) 
detags16 <- rownames(y)[as.logical(de16)]

de18<-decideTestsDGE(lrt18, p.value=0.05, lfc=1) 
detags18 <- rownames(y)[as.logical(de18)]

venn_name <- "/Users/miltr339/work/PhD_code/PhD_chapter4/data/DE_figures/DE_days_M_venn.png"
DE_genes <- list(d14 = detags14, d16 = detags16, d18 = detags18)
venn_plot <- venn.diagram(DE_genes, filename = venn_name, 
                          # output
                          imagetype="png" ,
                          height = 720 , 
                          width = 720 , 
                          resolution = 300,
                          compression = "lzw",
                          # circles
                          fill = c("#DE8F6E", "#2D93AD", "#88AB75"), 
                          lwd = 2,
                          lty = 'blank',
                          # Numbers
                          cex = .8,
                          main.fontface = "bold",
                          main.fontfamily = "sans",
                          fontface = "bold",
                          fontfamily = "sans",
                          cat.cex = 0.8, 
                          cat.fontface = "bold",
                          cat.default.pos = "outer",
                          cat.pos = c(-27, 27, 135),
                          cat.dist = c(0.055, 0.055, 0.085),
                          cat.fontfamily = "sans",
                          rotation = 1,
                          main="DE genes (q=0.05, lfc >1)")

```


